name: Build iOS dylib

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dylib
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)

          clang -dynamiclib \
            -arch arm64 \
            -isysroot $SDK \
            -miphoneos-version-min=13.0 \
            -framework Foundation \
            BlockNet.m \
            -o BlockNet.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlockNet-dylib
          path: BlockNet.dylib
