name: Build & Release iOS dylib

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build dylib
        run: |
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)

          clang -dynamiclib \
            -arch arm64 \
            -isysroot $SDK \
            -miphoneos-version-min=13.0 \
            -framework Foundation \
            BlockNet.m \
            -o BlockNet.dylib

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: BlockNet ${{ steps.version.outputs.VERSION }}
          files: BlockNet.dylib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
